using Norse.Abstractions.Contracts;

namespace Norse.Abstractions.Web.Server.Mediator;

/// <summary>
/// The closed-generic dispatch entry: resolves <see cref="IRequestHandler{TRequest,TResponse}"/>
/// and every <see cref="IBehavior{TRequest,TResponse}"/> from the scoped provider and folds them
/// around the handler, <b>first-registered outermost</b> — registration order in
/// <c>AddNorsePipeline()</c> is the chain order, and it is law (spec §2.2). A missing handler
/// registration fails loudly here (<see cref="ServiceProviderServiceExtensions.GetRequiredService{T}(IServiceProvider)"/>),
/// never silently no-ops.
///
/// This is also the platform's one and only cross-realm handler-uniqueness check. Registering
/// <see cref="ISenderDispatch"/> itself is deliberately idempotent (<c>TryAddEnumerable</c>,
/// generated by <c>RegistrationEmitter</c>) — the same realm's generated <c>AddNorse*Handlers()</c>
/// call landing twice in one composition root must collapse to one entry, because
/// <see cref="SenderDispatch{TRequest,TResponse}"/> is byte-identical regardless of which call
/// registered it and carries no notion of "which realm." That idempotency means a genuine
/// authoring conflict — two <em>different</em> realms both declaring an
/// <see cref="IRequestHandler{TRequest,TResponse}"/> for the same request type — can no longer be
/// caught by counting <see cref="ISenderDispatch"/> registrations upstream (see the correction to
/// Midgard's <c>SenderDispatchMap</c> doc comment, 2026-08-07). So the check moves here, to the one
/// place that actually knows how many distinct handler implementations answer this request type:
/// resolving <see cref="IRequestHandler{TRequest,TResponse}"/> as <c>IEnumerable</c> and requiring
/// exactly one. Zero throws the framework's own missing-registration message via
/// <see cref="ServiceProviderServiceExtensions.GetRequiredService{T}(IServiceProvider)"/>; more than
/// one throws a purpose-written <see cref="InvalidOperationException"/> naming the conflict, never
/// silently picking a winner. Stateless; registered as a singleton by generated code.
/// </summary>
public sealed class SenderDispatch<TRequest, TResponse> : ISenderDispatch<TResponse>
	where TRequest : IRequest<TResponse>
	where TResponse : notnull
{
	/// <inheritdoc />
	public Type RequestType =>
		typeof(TRequest);

	/// <inheritdoc />
	public ValueTask<Outcome<TResponse>> Dispatch(IServiceProvider services, IRequest<TResponse> request, CancellationToken cancellationToken = default)
	{
		var handler = ResolveHandler(services);
		var typed = (TRequest)request;
		BehaviorDelegate<TResponse> next = () => handler.Handle(typed, cancellationToken);
		foreach (var behavior in services.GetServices<IBehavior<TRequest, TResponse>>().Reverse())
		{
			var current = next;
			next = () => behavior.Handle(typed, current, cancellationToken);
		}

		return next();
	}

	/// <summary>
	/// Resolves exactly one <see cref="IRequestHandler{TRequest,TResponse}"/>, failing loudly on
	/// either side of "exactly one": zero delegates to <see cref="ServiceProviderServiceExtensions.GetRequiredService{T}(IServiceProvider)"/>
	/// for its standard missing-registration message; more than one is a cross-realm authoring
	/// conflict this platform never silently resolves by "last registration wins" — see the type's
	/// own doc comment for why this check lives here and not upstream in the dispatch map.
	/// </summary>
	static IRequestHandler<TRequest, TResponse> ResolveHandler(IServiceProvider services)
	{
		var handlers = services.GetServices<IRequestHandler<TRequest, TResponse>>().ToArray();
		return handlers.Length switch
		{
			0 => services.GetRequiredService<IRequestHandler<TRequest, TResponse>>(),
			1 => handlers[0],
			_ => throw new InvalidOperationException(
				$"Request type {typeof(TRequest).Name} has more than one IRequestHandler registered ({handlers.Length} found). A request type may be handled by exactly one realm — this is a cross-realm authoring conflict, not a valid composition."),
		};
	}
}
