<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="11.*-*" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="*" PrivateAssets="all" />
		<PackageReference Include="System.ServiceModel.Primitives" Version="*" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="11.*-*" />
		<ProjectReference Include="../../src/Abstractions.Contracts/Abstractions.Contracts.csproj" />
		<ProjectReference Include="../../gen/Abstractions.Contracts.Generator/Abstractions.Contracts.Generator.csproj" />
	</ItemGroup>
</Project>
